name: Build EXE with Pake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Pake
        run: npm install -g pake-cli

      - name: Build EXE
        run: pake .\MEXCCRM.html --name "MEXCCRM" --use-local-file --keep-binary

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MEXCCRM-build
          path: |
            **/*.exe
            **/*.msi
